import swiftsmith

import random
import sys

from datetime import date

if len(sys.argv) > 1:
    random.seed(sys.argv[1])
else:
    random.seed("swiftsmith")

print(f"\n// Generated by Swiftsmith on {date.today().strftime('%B %d, %Y')}")
x = swiftsmith.swift.randomtree()

rootscope = swiftsmith.Scope()
print(x.string(scope=rootscope))

f = rootscope.choose_function()
print(f"""
public func main(_ x: Int) -> Int {{
    return {f.name}({", ".join(k + ": x" for k in f.arguments)})
}}""")
